{"id": 616788, "name": "Shivaditya Bhattacharya", "username": "22f3000819", "avatar_template": "/user_avatar/discourse.onlinedegree.iitm.ac.in/22f3000819/{size}/66738_2.png", "created_at": "2025-04-07T20:42:10.131Z", "cooked": "<p><a class=\"mention\" href=\"/u/carlton\">@carlton</a> <a class=\"mention\" href=\"/u/jivraj\">@Jivraj</a><br>\nSir, in my docker logs, the datagen script encounters error during creating the credit card image for A8 during which it fails to find both the fonts used in the try and except blocks, resulting in the datagen script to stop abruptly without creating the files for A8 to A10.</p>\n<p><div class=\"lightbox-wrapper\"><a class=\"lightbox\" href=\"https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/a/4/a49f182e22015df35039be85cdd26ad71a07f7a3.png\" data-download-href=\"/uploads/short-url/nuja8ivRzao9XSmkZlLA9RYFAsP.png?dl=1\" title=\"image\" rel=\"noopener nofollow ugc\"><img src=\"https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/a/4/a49f182e22015df35039be85cdd26ad71a07f7a3.png\" alt=\"image\" data-base62-sha1=\"nuja8ivRzao9XSmkZlLA9RYFAsP\" width=\"690\" height=\"455\" data-dominant-color=\"313131\"><div class=\"meta\"><svg class=\"fa d-icon d-icon-far-image svg-icon\" aria-hidden=\"true\"><use href=\"#far-image\"></use></svg><span class=\"filename\">image</span><span class=\"informations\">1298\u00d7857 29.4 KB</span><svg class=\"fa d-icon d-icon-discourse-expand svg-icon\" aria-hidden=\"true\"><use href=\"#discourse-expand\"></use></svg></div></a></div></p>\n<p>I actually want to know if this could have been avoided by some changes in my code or is it an issue in the datagen.py script, because as the situation currently stands, my app wasn\u2019t even tested properly for tasks A8 to A10 as the datagen.py script failed to create the required files because it could not find a font which as far as I knew was not specified that it must be included in my own code or image somehow.</p>\n<p>Edit 1: I just realized that the datagen script looked for the fonts in python 3.13/site-packages/\u2026<br>\nBut my docker image is using the python:3.12-slim-bookworm. Could that be an issue? There was nothing specified about required python version or required python image to be used in docker in the project 1 requirements.</p>\n<p>Edit 2:<br>\nEven if the font not being available is somehow my fault, A9 and A10 still should not be penalized for A8 without proper checking.<br>\n<div class=\"lightbox-wrapper\"><a class=\"lightbox\" href=\"https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/5/f/5f99c9908823f381a7756ba6fe89d4827ca2faf4.png\" data-download-href=\"/uploads/short-url/dDIQy9HZw7zCPuZ0utgGoCbXRkM.png?dl=1\" title=\"image\" rel=\"noopener nofollow ugc\"><img src=\"https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/5/f/5f99c9908823f381a7756ba6fe89d4827ca2faf4.png\" alt=\"image\" data-base62-sha1=\"dDIQy9HZw7zCPuZ0utgGoCbXRkM\" width=\"690\" height=\"342\" data-dominant-color=\"F9F9F9\"><div class=\"meta\"><svg class=\"fa d-icon d-icon-far-image svg-icon\" aria-hidden=\"true\"><use href=\"#far-image\"></use></svg><span class=\"filename\">image</span><span class=\"informations\">1027\u00d7510 11 KB</span><svg class=\"fa d-icon d-icon-discourse-expand svg-icon\" aria-hidden=\"true\"><use href=\"#discourse-expand\"></use></svg></div></a></div><br>\nThough an error occured in A8, A9 and A10 still could have worked if each of these function calls were enclosed in their own try-except blocks, ensuring independent checks for each task. But the current datagen.py script fails as error propagates to main, where it is not handled and causes abnormal termination without executing the functions for creating files for A9 and A10 as well.</p>\n<p>Thank you.<br>\nRegards,<br>\nShivaditya</p>", "post_number": 432, "post_type": 1, "posts_count": 467, "updated_at": "2025-04-07T20:54:44.755Z", "reply_count": 2, "reply_to_post_number": null, "quote_count": 0, "incoming_link_count": 1, "reads": 63, "readers_count": 62, "score": 57.4, "yours": false, "topic_id": 171141, "topic_slug": "tds-official-project1-discrepencies", "display_username": "Shivaditya Bhattacharya", "primary_group_name": "ds-students", "flair_name": "ds-students", "flair_url": null, "flair_bg_color": "", "flair_color": "", "flair_group_id": 294, "badges_granted": [], "version": 3, "can_edit": false, "can_delete": false, "can_recover": false, "can_see_hidden_post": false, "can_wiki": false, "read": false, "user_title": "", "bookmarked": false, "actions_summary": [{"id": 2, "count": 2, "can_act": true}, {"id": 6, "can_act": true}, {"id": 3, "can_act": true}, {"id": 4, "can_act": true}, {"id": 8, "can_act": true}, {"id": 10, "can_act": true}, {"id": 7, "can_act": true}], "moderator": false, "admin": false, "staff": false, "user_id": 16002, "hidden": false, "trust_level": 1, "deleted_at": null, "user_deleted": false, "edit_reason": null, "can_view_edit_history": true, "wiki": false, "post_url": "/t/tds-official-project1-discrepencies/171141/432", "user_cakedate": "2023-01-25", "user_birthdate": "1904-03-07", "reactions": [{"id": "heart", "type": "emoji", "count": 2}], "current_user_reaction": null, "reaction_users_count": 2, "current_user_used_main_reaction": false, "can_accept_answer": false, "can_unaccept_answer": false, "accepted_answer": false, "topic_accepted_answer": null}