---
post_url: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/141
---
Hi [@carlton](/u/carlton) [@Jivraj](/u/jivraj),

I followed what you taught in Feb 11 session and tried implementing task A1. My understanding is once i run the subprocess, datagen.py file should be run and /data folder should be created in the project folder. But it is not happening to me. I am getting the following error

```
Traceback (most recent call last):
  File "/var/folders/rj/z_3b8hl51558519w90k5hp600000gn/T/datagen4COEF3.py", line 284, in <module>
    os.makedirs(config["root"], exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
OSError: [Errno 30] Read-only file system: '/data'

```

If i can’t automate this process, i don’t see the point writing code for other tasks. Can anyone help me solving this error?